/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sfa.voile.nav.astro.NavAstro;


import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;



public class AppTest {
    @BeforeAll
    static public void setupBeforeAll() {
        System.out.println("setupBeforeAll");
    }

    @AfterAll
    static public void cleanAfterAll() {
        System.out.println("cleanAfterAll");
    }

    @BeforeEach
    public void setupBefore() {
        System.out.println("setupBefore");
    }

    
    @AfterEach
    public void cleanAfter() {
        System.out.println("cleanAfter");
    }


    @Test
    public void appHasAGreeting() {
        App classUnderTest = new App();
        System.out.println("appHasAGreeting");
    }
}
