/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sfa.voile.nav.astro.NavAstro;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import sfa.voile.nav.astro.toolsUI.menus.MenuPrincipal;

public class App {

    public static void main(String[] args) {
        Logger logger = LoggerFactory.getLogger(App.class);
        logger.debug("Et c'est parti ...");
        
        try {
        	 MenuPrincipal.display();
        }
        catch(Exception e) {
            System.out.println(e.getMessage());
            e.printStackTrace();
        }
        logger.debug("... et c'est fini !");        
    }
}
