/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sfa.voile.nav.astro.NavAstro;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import sfa.voile.nav.astro.methodes.CalculsAstroDroiteHauteur;
import sfa.voile.nav.astro.methodes.CalculsAstroMeridienne;
import sfa.voile.nav.astro.methodes.CalculsAstroSoleil;
import sfa.voile.nav.astro.tools.menuUI;


public class App {

    public static void main(String[] args) {
        Logger logger = LoggerFactory.getLogger(App.class);
        logger.debug("Et c'est parti ...");
        
        try {
            App.start();
        }
        catch(Exception e) {
            System.out.println(e.getMessage());
            e.printStackTrace();
        }
        logger.debug("... et c'est fini !");        
    }
    
        public static void start() {
        menuUI _menu = new menuUI();
        
        while (true) {
            menuUI.eChoixMethodePrincipale methode = _menu.choixMethode();
            switch (methode) {
                case TheEnd: return;
                case DroiteDeHauteur: 
                    CalculsAstroDroiteHauteur.droiteHauteur(); 
                    break;
                case LatitudeMeridienne : 
                    CalculsAstroMeridienne.LatitudeMeridienne(); 
                    break;
                case DeclinaisonSolaire : 
                    CalculsAstroSoleil.DeclinaisonSolaire(); 
                    break;
                default:
                    throw new AssertionError();
            }
        }
    }
}
