/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sfa.nav;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test 
    public void appHasAGreeting() {
       String s = null;
        assertNotNull("app should have a greeting", s);
    }
}
